name: Build and Sync to Hugging Face Space
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install and Build
        run: |
          bun install
          bun run build

      - name: Push build to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "alpaim"
          SPACE_NAME: "alchemai"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME hf-space

          cd hf-space

          find . -maxdepth 1 ! -name '.git' ! -name 'README.md' ! -name '.' -exec rm -rf {} +

          cp -a ../dist/. .

          git lfs install

          git lfs track "*.wasm"

          git add .
          git commit -m "Auto-deploy new build" || echo "No changes to commit"
          git push
